# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://the.riturajps.in
date_format: "ordinal"
title: 码志
subtitle: "Public account: boring programmer"
description: "Expert SEO guides, tips and tricks. Free tutorials on HTML, CSS, JavaScript, web tools. Boost site traffic and search rankings with proven techniques."
keywords: riturajps, boring programmer
timezone: Asia/India
encoding: "utf-8"
# The year displayed in the lower left corner of the page
since: 2024
# Source code warehouse, please replace it with your own
repository: theriturajps/theriturajps.github.io
# CDN acceleration configuration for css and js resources
cdn:
     jsdelivr:
         enabled: false
# Optional component configuration
components:
     # share
     # weibo,qq,wechat,douban,qzone,linkedin,facebook,twitter
     share:
         enabled: false
         hide-platforms: qq,facebook
     # No garlic access statistics
     busuanzi:
         enabled: false
         start_date: 2020-05-03
     #My Popular Repositories
     side_bar_repo:
         enabled: true
         limit: 5
     #Article word count statistics
     word_count:
         enabled: true
     # The upper right corner of the page, and the QR code of the "About" page
     # To modify the image, please replace assets/images/qrcode.jpg
     qrcode:
         enabled: true
         image_alt: riturajps
     # Which view to use for the wiki index page, supports list/category
wiki:
         view: cate
     # Picture lightbox effect function
     fancybox:
         enabled: false
# Compress page content
compress_html:
   clippings: all
   comments: ["<!--", "-->"]
# Code highlighting style, the list of supported themes is available at https://github.com/mzlogin/rouge-themes
highlight_theme: github

#----------------#
# Author #
#----------------#
author: Ritu Raj
organization:
organization_url:
github_username: theriturajps
location: Delhi, India
email: iamriturajps@gmail.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
   -
     href: /
     label: Home

   -
     href: /categories/
     label: classification

   -
     href: /archives/
     label: archive
     mobile-hidden: true

   -
     href: /open-source/
     label: open source
     mobile-hidden: true

   -
     href: /fragments/
     label: fragment

   -
     href: /wiki/
     label: wiki

   -
     href: /links/
     label: link
     mobile-hidden: true

   -
     href: /about/
     label: about

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 10
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
plugins:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/
    fragments:
        output: true
        permalink: /fragment/:path/

#----------------#
# Comments #
#----------------#
# support provider: disqus, gitment, gitalk, utterances, beaudar, giscus
comments_provider: giscus
# !!!Important!!! Please modify the following information for your own application
# !!!Important!!! Please modify infos below to yours
# disqus configuration reference: https://disqus.com
disqus:
     username:
# gitment configuration reference: https://imsun.net/posts/gitment-introduction/
Gitment:
     owner: theriturajps
     repo: Comments
     oauth:
         client_id: *******************
         client_secret: *********************************
# gitalk configuration reference: https://github.com/gitalk/gitalk#install
gitalk:
     owner: theriturajps
     repo: Comments
     clientID: ****************
     clientSecret: ***************************
# utterances configuration reference: https://utteranc.es/
utterances:
     repo: theriturajps/Comments
# beaudar configuration reference: https://beaudar.lipk.org/
beaudar:
     repo: theriturajps/Comments
# giscus configuration reference: https://giscus.app/zh-CN
giscus:
     repo: theriturajps/Comments
     repo-id: R_kgDOLzGN0Q
     category: General
     category-id: DIC_kwDOLzGN0c4Ce8W3
# Click to display Disqus when using other comment components
lazy_load_disqus : true

#----------------#
# Search #
#----------------#
simple_jekyll_search:
     # Whether to support full text search
     fulltext: false
     #Maximum number of search results to display
     limit: 10

#----------------#
#Google#
#----------------#
google:
     analytics_id: # G-20FLEG5Q2W
     adsense:
         enabled: false
         footer: false
         sidebar: false
         sidebar-detail: false
         content_header: false
         content_footer: false